# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/amd/training/Reset/lab/KCU105/no_reset/no_reset.srcs/sources_1/ip/mmcm_clocks/mmcm_clocks.xci
# IP: The module: 'mmcm_clocks' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/amd/training/Reset/lab/KCU105/no_reset/no_reset.gen/sources_1/ip/mmcm_clocks/mmcm_clocks_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_clocks'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/amd/training/Reset/lab/KCU105/no_reset/no_reset.gen/sources_1/ip/mmcm_clocks/mmcm_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/amd/training/Reset/lab/KCU105/no_reset/no_reset.gen/sources_1/ip/mmcm_clocks/mmcm_clocks_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/amd/training/Reset/lab/KCU105/no_reset/no_reset.srcs/sources_1/ip/mmcm_clocks/mmcm_clocks.xci
# IP: The module: 'mmcm_clocks' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/amd/training/Reset/lab/KCU105/no_reset/no_reset.gen/sources_1/ip/mmcm_clocks/mmcm_clocks_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/amd/training/Reset/lab/KCU105/no_reset/no_reset.gen/sources_1/ip/mmcm_clocks/mmcm_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/amd/training/Reset/lab/KCU105/no_reset/no_reset.gen/sources_1/ip/mmcm_clocks/mmcm_clocks_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_clocks'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
