# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/amd/training/phys_opt/lab/KCU105/verilog/wave_gen.srcs/sources_1/ip/clk_core_phys_opt/clk_core_phys_opt.xci
# IP: The module: 'clk_core_phys_opt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/amd/training/phys_opt/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/clk_core_phys_opt/clk_core_phys_opt_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core_phys_opt'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/amd/training/phys_opt/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/clk_core_phys_opt/clk_core_phys_opt.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core_phys_opt'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/amd/training/phys_opt/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/clk_core_phys_opt/clk_core_phys_opt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core_phys_opt'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/amd/training/phys_opt/lab/KCU105/verilog/wave_gen.srcs/sources_1/ip/clk_core_phys_opt/clk_core_phys_opt.xci
# IP: The module: 'clk_core_phys_opt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/amd/training/phys_opt/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/clk_core_phys_opt/clk_core_phys_opt_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core_phys_opt'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/amd/training/phys_opt/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/clk_core_phys_opt/clk_core_phys_opt.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core_phys_opt'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/amd/training/phys_opt/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/clk_core_phys_opt/clk_core_phys_opt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core_phys_opt'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
